opendatamt/urls.py
#
#	author: Neil Barry-Murphy
#
#	Modified by David Kelly 03-04-2015
#	Moved all accounts urls to a separate django app 
#

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
from accounts import views

urlpatterns = patterns('',
	# Show login on homepage
	url(r'^$', views.login),
	# admin url
	url(r'^admin/', include(admin.site.urls)),
	#general app inclusions
	url(r'^comp_entries/', include('comp_entries.urls', namespace="comp_entries")),
    url(r'^uploader/', include('uploader.urls', namespace="uploader")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^teams/', include('teams.urls', namespace="teams")),
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
#
#	author: Neil Barry-Murphy
#

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('polls.views',
    # ex: /polls/
    url(r'^$', 'polls_home', name='polls_home'),
    # ex: /polls/5/
    url(r'^(?P<question_id>\d+)/$', 'detail', name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/results/$', 'results', name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', 'vote', name='vote'),
)

teams/urls.py
from django.conf.urls import patterns, url
from teams import views

urlpatterns = patterns('',
	url(r'^$', views.all_teams, name='all_teams'),
	url(r'^(?P<team_id>\d+)/$', views.team_info, name='team_info'),
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from teams.models import Team

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	team = models.ForeignKey(Team)

	def __str__(self):
		return self.user.username

teams/models.py
from django.db import models

class Team(models.Model):
	name = models.CharField(max_length=50)
	university = models.CharField(max_length=300, blank=True)
	
	def __unicode__(self):
		return self.name

teams/views.py
from django.shortcuts import render, get_object_or_404
from models import Team

# Create your views here.
def all_teams(request):
	teams = Team.objects.all()
	context = {'teams':teams}
	return render(request, 'teams/all_teams.html', context)

def team_info(request, team_id):
	team = get_object_or_404(Team, id=team_id)
	context = {'team':team}
	return render(request, 'teams/team_info.html', context)

teams/templates/teams/all_teams.html
{% extends "base.html" %}
{% block content %}
	<h2>All Teams</h2>
	{% if teams.count > 0 %}
		<ul>
		{% for team in teams %}
			<li><h4><a href="{% url 'teams:team_info' team.id %}">{{team.name}} - {{team.university}}</a></h4></li>
		{% endfor %}
	</ul>
	{% else %}
		<p>There are no teams to display.</p>
	{% endif %}
{% endblock content %}

teams/templates/teams/team_info.html
{% extends "base.html" %}
{% block content %}
	<h2>Team Info</h2>
	<h4>{{team.name}}</h4>
	<p>University: {{team.university}}</p>
	<br />
	<h4>Members:</h4>
	<ul>
	{% for member in team.userprofile_set.all %}
		<li>{{member.user.username}}</li>
	{% endfor %}
	</ul>
{% endblock content %}