comp_entries/urls.py
#
#	author: David Clince & Neil Barry-Murphy
#

from django.conf.urls import patterns, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('comp_entries.views',
	url(r'^$', 'entries_home', name='entries_home'),
	url(r'^(?P<comp_id>\d+)/$', 'entries_detail', name='entries_detail'),
	url(r'^search/$', 'search_titles', name='search_titles'),
)

opendatamt/urls.py
#
#	author: Neil Barry-Murphy
#
#	Modified by David Kelly 03-04-2015
#	Moved all accounts urls to a separate django app 
#

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
from accounts import views

urlpatterns = patterns('',
	# Show login on homepage
	url(r'^$', views.login),
	# admin url
	url(r'^admin/', include(admin.site.urls)),
	#general app inclusions
	url(r'^comp_entries/', include('comp_entries.urls', namespace="comp_entries")),
    url(r'^uploader/', include('uploader.urls', namespace="uploader")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^teams/', include('teams.urls', namespace="teams")),
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
#
#	author: Neil Barry-Murphy
#

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('polls.views',
    # ex: /polls/
    url(r'^$', 'polls_home', name='polls_home'),
    # ex: /polls/5/
    url(r'^(?P<question_id>\d+)/$', 'detail', name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/results/$', 'results', name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', 'vote', name='vote'),
)

teams/urls.py
from django.conf.urls import patterns, url
from teams import views

urlpatterns = patterns('',
	url(r'^$', views.all_teams, name='all_teams'),
	url(r'^(?P<team_id>\d+)/$', views.team_info, name='team_info'),
)

comp_entries/models.py
#
#	author: David Clince & Neil Barry-Murphy
#

from django.db import models
from datetime import datetime, timedelta
from django.contrib import admin
from teams.models import Team
from django.utils import timezone
	
class CompetitionManager(models.Manager):
	# Returns all active competitions
	def are_active(self):
		result = Competition.objects.all()
		for comp in result:
			if comp.still_active() is False: comp.delete()
		return result

	# Returns all active competitions for the given team
	def active_team_comps(self, team):
		result = Competition.objects.filter(teams=team)
		for comp in result:
			if comp.still_active() is False: comp.delete()
		return result

class Competition(models.Model):
	objects = CompetitionManager()
	teams = models.ManyToManyField(Team)
	name = models.CharField(max_length=50)
	description = models.TextField(max_length=2000)
	deadline_date = models.DateTimeField('deadline date')
	creation_date = models.DateTimeField('creation date')
	
	def __str__(self):
		return self.name
	
	def still_active(self):
		return timezone.now() <= self.deadline_date
	still_active.admin_order_field = 'creation_date'
	still_active.boolean = True
	still_active.short_description = 'Active?'

	def get_deadline_date():
		return datetime.today() + timedelta(days=30)

comp_entries/views.py
#
#   author: Neil Barry-Murphy
#
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from comp_entries.models import Competition

def entries_home(request):
    latest_comp_list = Competition.objects.order_by('-deadline_date')[:5]
    context = {'latest_comp_list': latest_comp_list, 'entries_home':Competition.objects.all()}
    return render(request, 'comp_entries/entries_home.html', context)

def entries_detail(request, comp_id):
    query = get_object_or_404(Competition, pk=comp_id)
    context = {'query':query}
    return render(request, 'comp_entries/entries_detail.html', context)

def search_titles(request):
    if request.method == "POST":
        search_text = request.POST['search_text']
    else:
        search_text = ''
    comp_entries = Competition.objects.filter(name__contains=search_text)
    context = {'comp_entries':comp_entries}
    return render(request, 'comp_entries/ajax_search.html', context)

comp_entries/templates/comp_entries/ajax_search.html
{% block content %}
<article class="topcontent">

{% if comp_entries.count > 0 %}

{% for competition in comp_entries %}
	<li><a href="/comp_entries/{{ competition.id }}/">{{ competition.name }}</a></li>
{% endfor %}

{% else %}
	<li>No links to show.</li>
{% endif %}
</article>

{% endblock content %}

comp_entries/templates/comp_entries/entries_detail.html
{% extends "base.html" %}
{% block toparticle %}
<article class="topcontent">

				<header>
					<h2>Competition: {{query.name}}</h2>
				</header>
					<h4>Deadline Date: {{query.deadline_date}}</h4>

				<content>
					<p>
						{{ query.description }}
					</p>
				</content>

				<h4>Teams Participating:</h4>
				<ul>
				{% for team in query.teams.all %}
					<li><a href="{% url 'teams:team_info' team.id %}">{{team.name}}</a></li>
				{% endfor %}
				</ul>
			</article>

{% endblock toparticle %}

comp_entries/templates/comp_entries/entries_home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extrahead %}
	<script src="{% static 'js/jquery-2.0.0.min.js' %}"></script>
	<script src="{% static 'js/ajax.js' %}"></script>
{% endblock extrahead %}

{% block toparticle %}
<article class="topcontent">
				<header>
					<h2>Search for an active competition</h2>
				</header>

				<content>
					<p>
						{% block content %}
						{% csrf_token %}
						<input type="text" id="search" name="search" />
						<ul id="search-results">

						</ul>
						{% endblock %}	
					</p>
				</content>
			</article>
{% endblock toparticle %}

{% block middlearticle %}
			<article class="middlecontent">

				<header>
					<h2>Current Competitions</h2>					
				</header>

				<content>
					<p>
						{% if latest_comp_list %}
						    <ul>
						    {% for query in latest_comp_list %}
								<li><a href="{% url 'comp_entries:entries_detail' query.id %}">{{ query.name }}</a></li>
						    {% endfor %}
						    </ul>
						{% else %}
						    <p>No competitions are currently available.</p>
						{% endif %}
					</p>
				</content>
			</article>
{% endblock middlearticle %}

comp_entries/templates/comp_entries/search.html
{% extends "base.html" %}
{% block toparticle %}
<article class="topcontent">
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}
    </form>
</article>
{% endblock toparticle %}