accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
	#user authentication urls
	url(r'^login/$', views.login, name='login'),
	url(r'^alt_login/$', views.alt_login, name='alt_login'),
	url(r'^auth/$', views.auth_view, name='auth_view'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^loggedin/$', views.loggedin, name='loggedin'),
	url(r'^invalid/$', views.invalid_login, name='invalid_login'),
	url(r'^not_a_team_member/$', views.need_team_membership, name='need_team_membership'),
	#registering users
	url(r'^register/$', views.register_user, name='register_user'),
	url(r'^register_success/$', views.register_success, name='register_success'),
)

comp_entries/urls.py
#
#	author: David Clince & Neil Barry-Murphy
#

from django.conf.urls import patterns, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('comp_entries.views',
	url(r'^$', 'entries_home', name='entries_home'),
	url(r'^(?P<comp_id>\d+)/$', 'entries_detail', name='entries_detail'),
	url(r'^search/$', 'search_titles', name='search_titles'),
)

opendatamt/urls.py
#
#	author: Neil Barry-Murphy
#
#	Modified by David Kelly 03-04-2015
#	Moved all accounts urls to a separate django app 
#

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
from accounts import views

urlpatterns = patterns('',
	# Show login on homepage
	url(r'^$', views.login),
	# admin url
	url(r'^admin/', include(admin.site.urls)),
	#general app inclusions
	url(r'^comp_entries/', include('comp_entries.urls', namespace="comp_entries")),
    url(r'^uploader/', include('uploader.urls', namespace="uploader")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^teams/', include('teams.urls', namespace="teams")),
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
#
#	author: Neil Barry-Murphy
#

from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('polls.views',
    # ex: /polls/
    url(r'^$', 'polls_home', name='polls_home'),
    # ex: /polls/5/
    url(r'^(?P<question_id>\d+)/$', 'detail', name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/results/$', 'results', name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', 'vote', name='vote'),
)

teams/urls.py
from django.conf.urls import patterns, url
from teams import views

urlpatterns = patterns('',
	url(r'^$', views.all_teams, name='all_teams'),
	url(r'^(?P<team_id>\d+)/$', views.team_info, name='team_info'),
)

uploader/urls.py
#
#	author: Neil Barry-Murphy
# 	Modified by David Kelly to work for saving competition submissions
#

from django.conf.urls import patterns, url
from django.contrib import admin
from uploader import views

admin.autodiscover()

urlpatterns = patterns('uploader.views',
	url(r'^$', views.home, name='upload'),
	url(r'^upload_complete/$', views.upload_complete, name='upload_complete'),
)

templates/base.html
<!DOCTYPE html>

<!--
    author: Neil Barry-Murphy
    Modifed by David Kelly
-->

{% load staticfiles %}

<head>
	<title>{% block title %}MT Competition Platform{% endblock title %}</title>
	{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
	<link rel="shortcut icon" type="image/x-icon" href="{% static "images/favicon.ico" %}" />
	{% endblock head %}
	{% block extrahead %} 
	{% endblock extrahead%}
</head>

<html lang="en">

{% block body %}
<body class="body">

	<header class="mainHeader">
		{% block header %}
		<nav><ul>
			<li><a href="{% url 'accounts:login' %}">Home</a></li>	
			<li><a href="{% url 'uploader:upload' %}">Upload</a></li>
			<li><a href="{% url 'comp_entries:entries_home' %}">Competitions</a></li>
			<li><a href="{% url 'polls:polls_home' %}">Upcoming Competitions</a></li>
			<li><a href="{% url 'teams:all_teams' %}">Teams</a></li>
			{% if user.is_authenticated %}
			<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
			{% else %}
			<li><a href="{% url 'accounts:alt_login' %}">Login</a></li>
			{% endif %}
		</ul></nav>
		{% endblock header %}
	</header>

	<div class="mainContent">
		<div class="content">
            
            {% block toparticle %}
            <!-- topcontent article-->
			<article class="topcontent">
				{% block content %}
				<header>
					<h2>Welcome</h2>
				</header>

				<footer>
					<p class="post-info"> </p>
				</footer>

				<content>
					<p> </p>
				</content>
				{% endblock content %}
			</article>
            <!-- end topcontent article-->
            {% endblock toparticle %}

            {% block middlearticle %}
            {% comment %}
            <!-- middlecontent article-->
			<article class="middlecontent">
				{% block middlecontent %}
				<header>
					<h2>Content ...</h2>
				</header>

				<footer>
					<p class="post-info"></p>
				</footer>

				<content>

				</content>
				{% endblock middlecontent %}
			</article>
            <!-- end middlecontent article-->
            {% endcomment %}
            {% endblock middlearticle %}

            {% comment %}
            {% block bottomcontent %}
            <!-- bottomcontent article-->
			<article class="bottomcontent">
				{% block bottomcontent %}
				<header>
					<h2>Content ...</h2>
				</header>

				<footer>
					<p class="post-info"></p>
				</footer>

				<content>

				</content>
				{% endblock bottomcontent %}
			</article>
            <!-- end bottomcontent article -->
            {% endblock bottomarticle %}
            {% endcomment %}
            
		</div><!-- End content div -->
	</div> <!-- End mainContent div-->

	{% block pagefooter %}
	<footer class="mainFooter">
		<p>Copyright &copy; 2015</p>
	</footer>
	{% endblock pagefooter %}

</body>
{% endblock body %}
</html>